services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Wegewerk\Ai3Alttext\:
    resource: '../Classes/*'
    exclude: '../Classes/Domain/Model/*'

  Wegewerk\Ai3Alttext\Domain\Capabilities\AlttextCapability:
    autowire: false
    arguments:
      $key: 'alttext'
      $title: 'Alt Text'
      $endpoint: '@Wegewerk\Ai3Alttext\Api\ZakAiAlttext'
    tags:
      - name: ai3.capability

  Wegewerk\Ai3Alttext\Api\ZakAiAlttext:
    arguments:
      $client: '@Wegewerk\Ai3Core\Api\ZakAiClient'
